### PR TITLE
Foundation Lightning Talk Presentation

### PR DESCRIPTION
**Pull request by jameye10**

### CODE REVIEW

**Comment by wesreisz** [comment]
Please don't delete the template. Just add yours. Correct and I will merge. If I merge yours, I will delete the template.

**Comment by jameye10** [comment]
Ok

Sent from my iPhone

On Apr 7, 2015, at 8:50 PM, Wesley Reisz <notifications@github.com<mailto:notifications@github.com>> wrote:

Please don't delete the template. Just add yours. Correct and I will merge. If I merge yours, I will delete the template.

##

**Comment by wesreisz** [comment]
Checkout your repo and run git checkout -- IgniteTemplate.ppt from the commandline. Then push and redo your pull request. That will restore the template. The only change you make should be to your presentation.

**Comment by jameye10** [comment]
I don't follow. I deleted my repo, then forked your repo again. After that, I never touched the template. I simply added my presentation and pushed it to my repo, Then attempted a pull request to yours. The git checkout -- IgniteTemplate.ppt does nothing from my commandline, so a push to mine and another pull request to yours would do nothing as well I'm assuming since it says everything is up to date.

**Comment by wesreisz** [comment]
Did you cancel the pull request and resend it after you did this? I am
unable to merge because of conflicts. The conflict I believe (I'm on my
phone right Noe so its harder to tell) is because of the template.
W

I don't follow. I deleted my repo, then forked your repo again. After that,
I never touched the template. I simply added my presentation and pushed it
to my repo, Then attempted a pull request to yours. The git checkout --
IgniteTemplate.ppt does nothing from my commandline, so a push to mine and
another pull request to yours would do nothing as well I'm assuming since
it says everything is up to date.

**Comment by wesreisz** [comment]
The pull request I have deletes the template (see attached). Cancel and
retry.
W
[image: Inline image 1]

**Comment by jameye10** [comment]
Ok

Sent from my iPhone

On Apr 8, 2015, at 10:49 AM, Wesley Reisz <notifications@github.com<mailto:notifications@github.com>> wrote:

The pull request I have deletes the template (see attached). Cancel and
retry.
W
[image: Inline image 1]

On Wed, Apr 8, 2015 at 10:39 AM, Wesley Reisz <wes@wesleyreisz.com<mailto:wes@wesleyreisz.com>> wrote:

> Did you cancel the pull request and resend it after you did this? I am
> unable to merge because of conflicts. The conflict I believe (I'm on my
> phone right Noe so its harder to tell) is because of the template.
> W
> 
> I don't follow. I deleted my repo, then forked your repo again. After
> that, I never touched the template. I simply added my presentation and
> pushed it to my repo, Then attempted a pull request to yours. The git
> checkout -- IgniteTemplate.ppt does nothing from my commandline, so a push
> to mine and another pull request to yours would do nothing as well I'm
> assuming since it says everything is up to date.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/wesreisz/cis411-lightningTalks/pull/4#issuecomment-90926062
> .

##

**Comment by jameye10** [comment]
I did not cancel the first pull request... I Just deleted my first repo, re-did everything and tried a new pull request

Sent from my iPhone

On Apr 8, 2015, at 10:39 AM, Wesley Reisz <notifications@github.com<mailto:notifications@github.com>> wrote:

Did you cancel the pull request and resend it after you did this? I am
unable to merge because of conflicts. The conflict I believe (I'm on my
phone right Noe so its harder to tell) is because of the template.
W

I don't follow. I deleted my repo, then forked your repo again. After that,
I never touched the template. I simply added my presentation and pushed it
to my repo, Then attempted a pull request to yours. The git checkout --
IgniteTemplate.ppt does nothing from my commandline, so a push to mine and
another pull request to yours would do nothing as well I'm assuming since
it says everything is up to date.

## 

Reply to this email directly or view it on GitHub
https://github.com/wesreisz/cis411-lightningTalks/pull/4#issuecomment-90926062
.

##

**Pull request closed without merging**
